### PR TITLE
Steel Tank fixes and IE Pipe hijacking

### PR DESCRIPTION
**Pull request by Kurtchekov**

### CODE REVIEW

**Comment by Kurtchekov** [comment]
@tgstyle please, check it out, this version should be compatible with all your savegames that used to crash when transitioning ;D

**Comment by tgstyle** [comment]
Can you make it a configurable option to disable, but enabled by default?

**Comment by Kurtchekov** [comment]
Should be doable, will do.

**Comment by Kurtchekov** [comment]
@tgstyle there you go, config option and even more improvements to the way those pesky pipes notify nearby TE's so that there's no accidental chunk loading.

**Pull request merged**
